version: "3.5"
services:
  extending:
    container_name: extending
    image: extending:latest
    ports:
      - target: 8080
        published: 8081
  myproject:
    container_name: myproject
    image: myproject:latest
    ports:
      - target: 8080
        published: 8080
